telegram-token: ""  # Insert telegram token here (in the form of 12345:AAABCD_DEFG)
telegram-chat-id: -1  # Insert telegram chat ID here (in the form of -1001234567890)
telegram-admin-chat-id: -1  # Insert admin telegram chat ID here (make sure only trusted users have write access to it)

telegram-list-message-id: 0  # Unless zero, updates message with that ID in the chat with actual player list
pinned-announcement: "[Автообновляется] "

# If player leaves and joins within {delete-rejoin-before} seconds, the "leave" message is removed
# instead of posting a "join" message
# Set to negative value to disable such behavior (it is enabled by default to prevent spamming with join messages)
delete-rejoin-before: 30

bridge-to-telegram:
  server-state:
    enable: true
    disable: true
  join-leave: true
  death: true
  advancements:
    goal: true
    challenge: true
    task: false
  messages: true
