name: Build plugin using Gradle

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build shadowJar with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: shadowJar
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: mctgbridge-jar
        path: build/libs/*.jar
        if-no-files-found: warn
        retention-days: 30
